apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: prod
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: master
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379